name: great_places
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  image_picker: ^0.6.1+4 # ALlows images to be taken with camera or gallery through app. For IOS requires special permission changes. https://pub.dev/packages/image_picker#ios
  path_provider: ^1.3.0 # Helps us find paths in the local file system - https://pub.dev/packages/path_provider#-readme-tab-
  path: ^1.6.4 # Allows us to join local file system paths -  https://pub.dev/packages/path#-readme-tab-
  location: ^2.3.5 # Allows usage of user location - https://pub.dev/packages/location # Be sure to edit AndroidManifest and Ios plist and gradle
  google_maps_flutter: ^0.5.21+3 # Allows usage of Google Maps inside the application - https://pub.dev/packages/google_maps_flutter # Be sure to edit androidManifest and plist and ios/runner/appdelegate.swift for iOS
  http:
    ^0.12.0+2 # allows http requests - https://pub.dev/packages/http#-readme-tab-
    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  simple_animations: ^1.3.3
  flutter_spinkit: ^4.1.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3" # Allows an icon to be used to represent the app

  # Sets up flutter_launcher_icons package
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-blue.png"
  adaptive_icon_background: "#ffffff" #Rounded app icon used in newer android
  adaptive_icon_foreground: "assets/images/logo-blue.png" #Rounded app icon used in newer android

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
